### ISSUE TITLE
External Function Call crashes if values are string

### ISSUE THREAD

**Issue by ZeAntwan** [smwhr/tinta#7]
Hello! 

I've been working on porting my project from Narrator to Tinta and ran into an issue.

For info, I am developing on Playdate, with the 2.4.2 SDK as of writing, using a Windows PC and Visual Code

I have an external function that takes strings for arguments. However, when the project hits it, an exception occurs in CallExternalFunction on line 1168 because the poppedObj does not contain a valueObj.

Note that I might be wrong in my assumtion, but here is the ink I use to test it using the tinta test project:

```
EXTERNAL phonebook(name,number)

=== start ===
This is a test for functions

~ phonebook("Emergency","922")

This is the end of the test

-> DONE
```

And my only addition to make it run on the test project were:
```
function addPhonebook(name,number)
    print(name)
end
```
Then right after the story is initialised
```
story:BindExternalFunction("phonebook", addPhonebook, true)
```

Followed by a ChoosePath at the end of the setupGame() function
```
story:ChoosePathString("start")
```

Hopefully that gives you enough information, let me know if there anything else I should try

And thanks for making this library!

**Comment by smwhr** [comment]
Pinging @Myonmu !

**Comment by Myonmu** [comment]
Fixed and pushed. @smwhr

The lua side external function only takes a table as its first parameter, you will need to get your desired value from the table.

For example:

```lua
function addPhonebook(args) 
    local name = args[1]
    local number = args[2]
end
```

**Comment by ZeAntwan** [comment]
Amazing! I tried that fix and now the function gets called, thanks for the added instructions!

However, another issue I ran into was that the function gets trigger twice now. In the test project i get this when ran:
```
Emergency
Loop 1
Emergency
Loop 2
```

Is that expected?

**Comment by Myonmu** [comment]
> Amazing! I tried that fix and now the function gets called, thanks for the added instructions!
> 
> However, another issue I ran into was that the function gets trigger twice now. In the test project i get this when ran:
> ```
> Emergency
> Loop 1
> Emergency
> Loop 2
> ```
> 
> Is that expected?
> 

Hmmm, I did noticed that under some circumstances the function can be called twice, but in my case it was an ill-written ink. What ink are you using that produced this result?

**Comment by ZeAntwan** [comment]
Exactly the same as my initial post, no change. Let me send you the zip of the ink, json and lua export I've got
[tinta.zip](https://github.com/smwhr/tinta/files/14883509/tinta.zip)

**Comment by smwhr** [comment]
IIRC, that's expected, the engine sometimes execute some part of ink twice ("lookAhead") to deal with newlines and glue.
The original code has a `lookAheadSafe` parameter to deal with that.

**Comment by ZeAntwan** [comment]
Yes, I've been exploring the code a bit, and saw that complete comment next to the function at line 1183 of the story.lua file, meaning that, if I understood correctly, if I want that function to be only executed once, I should set the last argument to that Binding function to false 
``` lua
---Bind a lua function to an ink EXTERNAL function declaration.
---@param funcName string EXTERNAL ink function name to bind to.
---@param func function The lua function to bind.
---@param lookaheadSafe boolean the ink engine often evaluates further
---than you might expect beyond the current line just in case it sees 
---glue that will cause the two lines to become one. In this case it's 
---possible that a function can appear to be called twice instead of 
---just once, and earlier than you expect. If it's safe for your 
---function to be called in this way (since the result and side effect 
---of the function will not change), then you can pass 'true'. 
---Usually, you want to pass 'false', especially if you want some action 
---to be performed in game code when this function is called.
function Story:BindExternalFunction(funcName, func, lookaheadSafe)
```

But I then instead run into this error for which I'll try the suggested workaround
``` lua
error("External function "..funcName.." could not be called because 1) it wasn't marked as lookaheadSafe when BindExternalFunction was called and 2) the story is in the middle of string generation, either because choice text is being generated, or because you have ink like \"hello {func()}\". You can work around this by generating the result of your function into a temporary variable before the string or choice gets generated: ~ temp x = "..funcName.."()")
```

Although it feels like my case doesn't match what the error describes here

**Comment by Myonmu** [comment]
I tested the same ink with C# and tinta doesn't have the same behaviour. I'll have to look deeper into it. This can be tricky to debug though.

**Comment by Myonmu** [comment]
Now it should work. The default behaviour is now *not look ahead safe* when binding a function (so you don't need to pass the third parameter when binding). When it is *look ahead safe*, it will still be invoked twice which is the same behaviour as the C# version.

**Comment by ZeAntwan** [comment]
All working on my end too! Thanks for these quick fixes! 
I might run into other issue, but I'll make a new one to avoid changing this one too much over time for posterity 😁
And I'll make sure to check against ink documentation to see if what I'm noticing is a bug or a feature I need to add on my end

I'll let you close it whenever you feel is right (probably once the merge has been accepted)

**Comment by smwhr** [comment]
Merged and closing !
Thank you for everything !
